"""add_scene_video_fields

Revision ID: b313cffa372b
Revises: 875c67134df5
Create Date: 2026-04-06 09:19:12.901873+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b313cffa372b'
down_revision: Union[str, None] = '875c67134df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('video_prompt', sa.String(), nullable=True))
    op.add_column('scenes', sa.Column('video_url', sa.String(length=1024), nullable=True))
    op.add_column('scenes', sa.Column('video_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'video_status')
    op.drop_column('scenes', 'video_url')
    op.drop_column('scenes', 'video_prompt')
    # ### end Alembic commands ###
